### ISSUE TITLE
アイテム一覧のyamlを作成

### ISSUE THREAD

**Issue by mitsuru793** [matthew70/vainglory#16]
2段階まではステータス上昇のみなので、下記のフォーマットで大丈夫だと思います。
※ utilityは除く。

``` yaml
piercing_spear:
  kind: weapon
  gold: 900
  improve:
    weapon_power: 15%
    armor_pierce: 10%
  from:
    - weapon_blade
  to:
    - tension_bow
    - bonesaw
```

問題は条件により値が変動するものです。これは #11と同じ問題です。例えばトラベルブーツだと、次のように変動します。

> パッシブ：移動速度+0.45。戦闘中でなければさらに+1。

そのため、まずは下記の項目を全て列挙します。
- 種類（配列）
- 値段
- クールダウン
- アップグレード先（配列）
- ダウングレード先（配列）
- 段階
