### ISSUE TITLE
ヒーローのステータスのyamlに余分なハッシュ

### ISSUE THREAD

**Issue by mitsuru793** [matthew70/vainglory#5]
``` ruby
{:name=>"Rona",
 :status=>
  [[{:name=>"hp"}, {:start=>799.0}, {:glow=>90.0}],
   [{:name=>"hp_regen"}, {:start=>nil}, {:glow=>nil}],
   [{:name=>"weapon_damage"}, {:start=>88.0}, {:glow=>6.2}],
   [{:name=>"attack_speed"}, {:start=>1.0}, {:glow=>0.012}],
   [{:name=>"armor"}, {:start=>20.0}, {:glow=>6.0}],
   [{:name=>"shield"}, {:start=>20.0}, {:glow=>6.0}],
   [{:name=>"attack_range"}, {:start=>1.8}, {:glow=>nil}],
   [{:name=>"move_speed"}, {:start=>3.3}, {:glow=>nil}]]}
```

試しにロナのデータを読み込むと分かりますが、`[{:name=>"hp"}, {:start=>799.0}, {:glow=>90.0}],`は`{:name=>"hp", :start=>799.0, :glow=>90.0},`という形で済むはずです。

つまり、今は1つのステータスが1つのハッシュではなく、各項目を1つのハッシュとした配列になっています。

**Comment by Imfloppy** [comment]
そうなのですよね。`{:name=>"hp", :start=>799.0, :glow=>90.0}` の形に出来たほうがシンプルで良いかもしれません。
実は、私の方でもyamlの形式をちょっと変えたいなぁと考えていました。

```
Rona:
  hp:
    start: 799.0
    glow: 90.0
  hp_regen:
    start:
    glow:
  weapon_damage:
    start: 88.0
    glow: 6.2
  attack_speed:
    start: 1.0
    glow: 0.012
  armor:
    start: 20.0
    glow: 6.0
  shield:
    start: 20.0
    glow: 6.0
  attack_range:
    start: 1.8
    glow:
  move_speed:
    start: 3.3
    glow:
```

こんな形式になるといい気がしています。トップレベルを配列ではなくてハッシュにしてしまえば

```
status_data = YAML.load_file(File.expand_path(...))
status_data['Rona']
status_data['Rona']['hp']['start']
```

という感じでアクセスできます。どうでしょ？
（修正は私の方でも対応可です）
